import React from 'react'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { Button } from '@/components/ui/button'
import { SessionDetail } from '../../medical-agent/[sessionId]/page'
import moment from 'moment'
import { Separator } from '@/components/ui/separator'


type Props = {
    record: SessionDetail
}
function ViewReportDialog({record}:Props) {
  return (
    <Dialog>
  <DialogTrigger>
    <Button variant={'link'} size={'sm'}>View Report</Button>
  </DialogTrigger>
  <DialogContent className="max-h-[85vh] overflow-y-auto">
    <DialogHeader>
      <DialogTitle asChild><h2 className='text-center font-bold text-blue-500 text-4xl'>Medical AI Medical Agent's report </h2></DialogTitle>
      <DialogDescription asChild>
        <div className='mt-10 space-y-10'>
          <div className='mt-10'>
            <h2 className='font-bold text-blue-500 text-lg'>Consultation Info:</h2>
            <Separator className=' bg-blue-500'/>
            
       <div className='grid grid-cols-2'>

    <h2 className='mt-5'> <span className='font-bold'>Doctor Specilization:</span> {record?.selectedDoctor?.specialist} </h2>
    <p className='mt-5'> <span className='font-bold'>Description: </span>{record?.selectedDoctor?.description}</p>
    <h2 className='mt-5'> <span className='font-bold'>Date: </span>{moment(new Date(record?.createdOn)).fromNow()}</h2>
    <h2 className='mt-5'> <span className='font-bold'>Agent: </span>{record?.report?.agent}</h2>
       </div>
</div>

   


     <div className='mt-10'>
            <h2 className='font-bold text-blue-500 text-lg'>Chief Complaint:</h2>
            <Separator className=' bg-blue-500'/>
       <div className='grid grid-cols-2'>

    <h2 className='mt-5'>{JSON.stringify(record?.report?.chiefComplaint)}</h2>

       </div>
    </div>

   <div className='mt-10'>
            <h2 className='font-bold text-blue-500 text-lg'>Summary:</h2>
            <Separator className=' bg-blue-500'/>
       <div className='grid grid-cols-2'>

    <h2 className='mt-5'>{JSON.stringify(record?.report?.summary)}</h2>

       </div>
    </div>
<div className='mt-10'>
            <h2 className='font-bold text-blue-500 text-lg'>Symptoms:</h2>
            <Separator className=' bg-blue-500'/>
       <div className='grid grid-cols-2'>

    <h2 className='mt-5'>{JSON.stringify(record?.report?.symptoms)}</h2>

       </div>
    </div>
<div className='mt-10'>
            <h2 className='font-bold text-blue-500 text-lg'>Duration & Severity:</h2>
            <Separator className=' bg-blue-500'/>
       <div className='grid grid-cols-2'>

     <h2 className='mt-5'> <span className='font-bold'>Duration:</span> {record?.report?.duration} </h2>
    <h2 className='mt-5'> <span className='font-bold'>Description: </span>{record?.report?.severity}</h2>

       </div>
    </div>
<div className='mt-10'>
            <h2 className='font-bold text-blue-500 text-lg'>Medications:</h2>
            <Separator className=' bg-blue-500'/>
       <div className='grid grid-cols-2'>

    <h2 className='mt-5'>{JSON.stringify(record?.report?.medicationsMentioned)}</h2>

       </div>
    </div>

<div className='mt-10'>
            <h2 className='font-bold text-blue-500 text-lg'>Recommendations:</h2>
            <Separator className=' bg-blue-500'/>
       <div className='grid grid-cols-2'>

    <h2 className='mt-5'>{JSON.stringify(record?.report?.recommendations)}</h2>

       </div>
    </div>
 <div className='mt-10'>
   <Separator className=' bg-gray-500'/>
   <h2 className='font-bold mt-5'>This report was generated by our AI Medical Agent: {record?.selectedDoctor?.specialist} </h2>
 </div>
        </div>

        

      </DialogDescription>
    </DialogHeader>
  </DialogContent>
</Dialog>
  )
}

export default ViewReportDialog